# Generated by Django 5.0.7 on 2024-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0005_remove_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
