# Generated by Django 5.0.7 on 2024-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_dongdaemoon_remove_board_user_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='gu',
        ),
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.CharField(max_length=100),
        ),
    ]
