# Generated by Django 5.0.7 on 2024-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_board_gu_alter_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='gu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
