# Generated by Django 5.0.7 on 2024-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_gu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='blogcnt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='maindoctorcnt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='visitcnt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
