# Generated by Django 5.0.7 on 2024-07-30 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0010_alter_board_blogcnt_alter_board_maindoctorcnt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dongdaemoon",
        ),
    ]
